// Copyright 2016 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "components/ui_citizennotes/citizennotes_client.h"

#include "components/ui_citizennotes/citizennotes_server.h"
#include "third_party/inspector_protocol/crdtp/dispatch.h"
#include "third_party/inspector_protocol/crdtp/json.h"

namespace ui_citizennotes {

UiCitizenNotesClient::UiCitizenNotesClient(const std::string& name,
                                   UiCitizenNotesServer* server)
    : name_(name),
      connection_id_(kNotConnected),
      dispatcher_(this),
      server_(server) {
  DCHECK(server_);
}

UiCitizenNotesClient::~UiCitizenNotesClient() {}

void UiCitizenNotesClient::AddAgent(std::unique_ptr<UiCitizenNotesAgent> agent) {
  agent->Init(&dispatcher_);
  agents_.push_back(std::move(agent));
}

void UiCitizenNotesClient::Disconnect() {
  connection_id_ = kNotConnected;
  DisableAllAgents();
}

void UiCitizenNotesClient::Dispatch(const std::string& json) {
  std::vector<uint8_t> cbor;
  crdtp::Status status =
      crdtp::json::ConvertJSONToCBOR(crdtp::SpanFrom(json), &cbor);
  if (!status.ok()) {
    dispatcher_.channel()->SendProtocolNotification(
        crdtp::CreateErrorNotification(
            crdtp::DispatchResponse::ParseError(status.ToASCIIString())));
    return;
  }
  crdtp::Dispatchable dispatchable(crdtp::SpanFrom(cbor));
  if (dispatchable.ok()) {
    dispatcher_.Dispatch(dispatchable).Run();
    return;
  }
  if (dispatchable.HasCallId()) {
    dispatcher_.channel()->SendProtocolResponse(
        dispatchable.CallId(),
        crdtp::CreateErrorResponse(dispatchable.CallId(),
                                   dispatchable.DispatchError()));
  } else {
    dispatcher_.channel()->SendProtocolNotification(
        crdtp::CreateErrorNotification(dispatchable.DispatchError()));
  }
}

bool UiCitizenNotesClient::connected() const {
  return connection_id_ != kNotConnected;
}

void UiCitizenNotesClient::set_connection_id(int connection_id) {
  connection_id_ = connection_id;
}

const std::string& UiCitizenNotesClient::name() const {
  return name_;
}

void UiCitizenNotesClient::DisableAllAgents() {
  for (std::unique_ptr<UiCitizenNotesAgent>& agent : agents_)
    agent->Disable();
}

void UiCitizenNotesClient::MaybeSendProtocolResponseOrNotification(
    std::unique_ptr<protocol::Serializable> message) {
  if (!connected())
    return;

  std::string json;
  crdtp::Status status = crdtp::json::ConvertCBORToJSON(
      crdtp::SpanFrom(message->Serialize()), &json);
  DCHECK(status.ok());  // CBOR was generated by Chrome, so we expect it's ok.
  server_->SendOverWebSocket(connection_id_, base::StringPiece(json));
}

void UiCitizenNotesClient::SendProtocolResponse(
    int callId,
    std::unique_ptr<protocol::Serializable> message) {
  MaybeSendProtocolResponseOrNotification(std::move(message));
}

void UiCitizenNotesClient::SendProtocolNotification(
    std::unique_ptr<protocol::Serializable> message) {
  MaybeSendProtocolResponseOrNotification(std::move(message));
}

void UiCitizenNotesClient::FlushProtocolNotifications() {
  NOTIMPLEMENTED();
}

void UiCitizenNotesClient::FallThrough(int call_id,
                                   crdtp::span<uint8_t> method,
                                   crdtp::span<uint8_t> message) {
  NOTIMPLEMENTED();
}

}  // namespace ui_citizennotes
